import type { Metadata } from "next";

import './globals.css'

import localFont from "next/font/local";

const gopher = localFont({
  src: "../public/gopher1.ttf",
  variable: "--font-gopher",

});

const tattosWishe = localFont({
  src: "../public/tatto.otf",
  variable: "--font-tattos-wishe",
});


// app/layout.tsx
export const metadata: Metadata = {
  title: "Lilac Template",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/backli.jpg",
        type: "image/jpeg", // Specify the type
      },
      // Add fallback favicon.ico for older browsers
      "/favicon.ico",
    ],
    shortcut: "/backli.jpg",
    apple: "/backli.jpg", // For Apple devices
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${gopher.variable} ${tattosWishe.variable} `}

      >

        {children}
      </body>
    </html>
  );
}
