import type { Metadata } from "next";

import './globals.css'

import localFont from "next/font/local";

const gopher = localFont({
  src: "../public/gopher1.ttf",
  variable: "--font-gopher",
  
});

const tattosWishe = localFont({
  src: "../public/tatto.otf",
  variable: "--font-tattos-wishe",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gopher.variable} ${tattosWishe.variable} `}

      >
        
        {children}
      </body>
    </html>
  );
}
